# This is a basic workflow to help you get started with Actions

name: Test

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: "test debug value"
        required: true
        type: string
        default: "info"

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print the input tag to STDOUT
      env:
        LOG: ${{ inputs.logLevel || 'DEBUG' }}
      run: | 
        echo "checking input ${{ inputs.logLevel }}"
        echo "checking step var $LOG"
        echo "logLevel=${{ inputs.logLevel || 'Yellow' }}" >> $GITHUB_ENV
        echo "checking env var ${{ env.logLevel }}"

    
